# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(266, 202)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.url_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.url_edit.setObjectName("url_edit")
        self.gridLayout.addWidget(self.url_edit, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.account_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.account_edit.setObjectName("account_edit")
        self.gridLayout.addWidget(self.account_edit, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.passwor_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.passwor_edit.setObjectName("passwor_edit")
        self.gridLayout.addWidget(self.passwor_edit, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.addr_edit = QtWidgets.QLineEdit(self.centralwidget)
        self.addr_edit.setObjectName("addr_edit")
        self.gridLayout.addWidget(self.addr_edit, 3, 1, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.log_button = QtWidgets.QPushButton(self.centralwidget)
        self.log_button.setObjectName("log_button")
        self.horizontalLayout.addWidget(self.log_button)
        self.restart_button = QtWidgets.QPushButton(self.centralwidget)
        self.restart_button.setObjectName("restart_button")
        self.horizontalLayout.addWidget(self.restart_button)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.update_button = QtWidgets.QPushButton(self.centralwidget)
        self.update_button.setObjectName("update_button")
        self.horizontalLayout_2.addWidget(self.update_button)
        self.web_button = QtWidgets.QPushButton(self.centralwidget)
        self.web_button.setObjectName("web_button")
        self.horizontalLayout_2.addWidget(self.web_button)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.gridLayout.addLayout(self.verticalLayout, 4, 0, 1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "hk web tool"))
        self.label.setText(_translate("MainWindow", "URL"))
        self.label_2.setText(_translate("MainWindow", "account"))
        self.label_3.setText(_translate("MainWindow", "password"))
        self.label_4.setText(_translate("MainWindow", "pack addr"))
        self.log_button.setText(_translate("MainWindow", "log in"))
        self.restart_button.setText(_translate("MainWindow", "restart"))
        self.update_button.setText(_translate("MainWindow", "update"))
        self.web_button.setText(_translate("MainWindow", "open"))
